# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chacho' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chacho
  pod 'AppCenter/Crashes', '~> 1.6.0'
  pod 'AppCenter/Analytics', '~> 1.6.0'
  pod 'AppCenterReactNativeShared', '~> 1.5.0'

  

  platform :ios, '9.0'
  target 'chachoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'chacho-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chacho-tvOS

  target 'chacho-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
